language: node_js
sudo: required
addons:
  chrome: stable
script: karma start karma.conf.js --single-run 
os: osx
before_script:
  - npm install -g karma-cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_install:
  - "export CHROME_BIN=chromium-browser" 
  - export DISPLAY=:99.0
node_js:
  - "node"
  - "8.11.1" 